### ISSUE TITLE
Redo tests starting from 12cR2 affected by redo optimization

### ISSUE THREAD

**Issue by MarisElsins** [therealkevinc/SLOB_distribution#1]
Hi Kevin, 

Starting with 12cR2 the HEAVY redo mode (and I think the LIGHT too) does not produce the same volumes of redo as it used to before 12cR1 due to optimization I described in https://blog.pythian.com/redo-volume-optimization-in-12c-r2/

I think it'd be useful to modify the SLOB so that the the testing worked around the optimization described. I attempted a quick workaround (https://gitlab.com/MarisElsins/Public/snippets/1728857) and it worked nicely for my tests, but it may not be optimal under more capable systems as I think it might show some contention in obtaining the current SCN. Probably a global PL/SQL variable would be a better option for generating different values to use in the update statements.

P.S. reporting it here as I couldn't find a better way to reach you.
P.S.2. I'll remove the snippet from the Gitlab once you've seen it.

Maris

**Comment by MarisElsins** [comment]
Fixed in SLOB 2.5.0! 
Thanks, Kevin!

**Comment by therealkevinc** [comment]
No! Thank you!!

Sent from Yahoo Mail on Android 
 
  On Sat, Oct 5, 2019 at 12:01, Maris Elsins<notifications@github.com> wrote:   
Fixed in SLOB 2.5.0!
Thanks, Kevin!
